{% set name = "chafa" %}
{% set version = "1.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpjansson/{{ name }}/releases/download/{{ version }}/chafa-{{ version }}.tar.xz
  sha256: 4a25debb71530baf0a748b15cfee6b8da6b513f696d9484987eaf410ecce1129

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - make
  host:
    - freetype
    - cairo
    - glib
    - libjpeg-turbo
    - librsvg
    - libtiff
    - libwebp
    - libavif
    - libjxl
    - libpng  # [linux]
    - zlib  # [linux]
    - gdk-pixbuf  # [osx]
    - libintl-devel  # [osx]
  run:

test:
  commands:
    - chafa --version

about:
  home: https://hpjansson.org/chafa
  summary: Versatile and fast Unicode/ASCII/ANSI graphics renderer
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/hpjansson/chafa

extra:
  recipe-maintainers:
    - pavelzw
    - eunos-1128
    - peterjc
